Camelot/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'camelot'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('foo/<int:number>/', views.FooView.as_view()),
    path('liuyan/', views.liuyan, name='liuyan'),
    path('shoppingcart/', views.shoppingcartview, name='shoppingcart'),
    path('detail/<int:product_id>/', views.detail, name="detail"),
    path('dongman/', views.dongman, name='dongman'),
    path('mingxing/', views.mingxing, name='mingxing'),
    path('piaowu/', views.piaowu, name='piaowu'),
    path('xiaoshuo/', views.xiaoshuo, name='xiaoshuo'),
    path('yingshi/', views.yingshi, name='yingshi'),
    path('youxi/', views.youxi, name='youxi'),
    path('shuji/', views.shuji, name='shuji'),
    path('yingyuan/', views.yingyuan, name='yingyuan'),
    path('hufu/', views.hufu, name='hufu'),
    path('shuma/', views.shuma, name='shuma'),
    path('riyong/', views.riyong, name='riyong'),
    path('fuzhuang/', views.fuzhuang, name='fuzhuang'),
    path('jiaru/', views.jiaru, name='jiaru'),
    path('settlement/', views.settlement, name='settlement'),
    path('payment/', views.payment, name='payment')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Camelot.urls')),
]

Camelot/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass


class Counter(models.Model):
    counter = models.IntegerField(default=0)

    def __str__(self):
        return self.id


class Liuyan(models.Model):
    username = models.CharField(max_length=200)
    liuyan = models.CharField(max_length=2000)

    def __str__(self):
        return self.liuyan


class ShoppingCart(models.Model):
    user = models.ForeignKey('Camelot.User', on_delete=models.CASCADE, related_name='cart')
    product = models.ForeignKey('Camelot.Product', on_delete=models.CASCADE, related_name='cart')
    ordercount = models.IntegerField()


class Product(models.Model):
    productid = models.IntegerField()
    name = models.CharField(max_length=120)
    imagesrc = models.CharField(max_length=2000)
    price = models.IntegerField()
    shopid = models.IntegerField()
    info = models.CharField(max_length=2000)
    jieshao = models.CharField(max_length=5000)
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.name

Camelot/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpRequest
from django.core import serializers
from django.views.generic import View
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView as LoginViewBase
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Counter
import json
from .models import User, Liuyan, ShoppingCart, Product
from django.views.decorators.csrf import csrf_exempt

def index(request):
    a = Counter.objects.get(id=1)
    a.counter += 1
    a.save()

    return render(request, 'index.html', {'data': a.counter})


class LoginView(LoginViewBase):

    template_name = 'login.html'
    # def get(self, request):
    #     return render(request, 'login.html')
    #
    # def post(self, request):
    #     # body_json = json.loads(request.body)
    #     #
    #     # print(body_json)
    #     #
    #     # username = body_json['username']
    #     # password = body_json['password']
    #     #
    #     # user = authenticate(request, username=username, password=password)
    #     # if user is None:
    #     #     return HttpResponse(json.dumps({'success': False}), content_type='application/json; charset=utf-8')
    #     # return HttpResponse(json.dumps({'success': True}), content_type='application/json; charset=utf-8')
    #     print(request.POST)
    #
    #     username = request.POST.get('username')
    #     password = request.POST.get('password')
    #
    #     user = authenticate(request, username=username, password=password)
    #     if user is None:
    #         return HttpResponse('Fail')
    #     login(request, user)
    #     return HttpResponse('OK')




class FooView(LoginRequiredMixin, View):
    def get(self, request, number):
        return HttpResponse('Login Success')


class RegisterView(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        user_name = request.POST.get('username')
        pass_word = request.POST.get('password')
        mmm = User.objects.create_user(user_name, 'lennon@thebeatles.com', pass_word)
        mmm.save()
        return redirect('/login')


@csrf_exempt
def liuyan(request):
    if request.method == 'GET':
        # jvzi = Liuyan.objects.all()

        # print(jvzi[0].id)
        items = Liuyan.objects.all()
        return render(request, 'liuyan.html', {'items': items})

    if request.method == 'POST':
        # body_json = json.loads(request.body)
        # body_json = json.loads(request.body)
        # print(body_json)
        print(request.body.decode('utf-8'))
        liuyan = request.body.decode('utf-8')

        q = Liuyan(username=request.user.username,liuyan= liuyan)
        q.save()
        return HttpResponse(request.body)
    else:
        pass


@csrf_exempt
def shoppingcartview(request):
    if not request.user.is_authenticated:
        return redirect('/login')

    if request.method == 'GET':
        return render(request, 'shoppingcart.html')

    if request.method == 'POST':

        ls = []
        items = request.user.cart.all()

        for item in items:
            a = {
                'id': item.product.productid,
                'src': item.product.imagesrc,
                'name': item.product.name,
                'info': item.product.info,
                'price': item.product.price,
                'shopid': item.product.shopid,
                'ordercount': item.ordercount
            }
            ls.append(a)
        ms = {"data": ls}

        data = json.dumps(ms)
        return HttpResponse(data, content_type='application/json; charset=utf-8')


@csrf_exempt
def detail(request, product_id):
    s = Product.objects.get(productid=product_id)
    return render(request, 'detail.html', {'item': s})


@csrf_exempt
def jiaru(request):

    if request.user.is_authenticated:
        if request.method == 'POST':
            json_data = json.loads(request.body)
            productid = int(json_data['id'])
            print(productid)
            me = request.user
            print(me)
            c = ShoppingCart(user=me,
                         product=Product.objects.get(productid=productid),
                         ordercount=1)
            c.save()

            return HttpResponse('ok')
        else:
             pass
    else:
        return HttpResponse('qvdenglu')



@csrf_exempt
def settlement(request):
    return render(request, 'settlement.html')


@csrf_exempt
def payment(request):
    return render(request, 'payment.html')





@csrf_exempt
def mingxing(request):
    items = Product.objects.filter(category='mingxing')
    a = Counter.objects.get(id=1)
    return render(request, 'mingxing/mingxing.html', {'data': a.counter, 'items': items})


@csrf_exempt
def piaowu(request):
    items = Product.objects.filter(category='piaowu')
    a = Counter.objects.get(id=1)
    return render(request, 'piaowu/piaowu.html', {'data': a.counter, 'items': items})


@csrf_exempt
def xiaoshuo(request):
    items = Product.objects.filter(category='xiaoshuo')
    a = Counter.objects.get(id=1)
    return render(request, 'xiaoshuo/xiaoshuo.html', {'data': a.counter, 'items': items})


@csrf_exempt
def yingshi(request):
    items = Product.objects.filter(category='yingshi')
    a = Counter.objects.get(id=1)
    return render(request, 'yingshi/yingshi.html', {'data': a.counter, 'items': items})


@csrf_exempt
def dongman(request):
    items = Product.objects.filter(category='dongman')
    a = Counter.objects.get(id=1)
    return render(request, 'dongman/dongman.html', {'data': a.counter, 'items': items})

@csrf_exempt
def youxi(request):
    items = Product.objects.filter(category='youxi')
    a = Counter.objects.get(id=1)
    return render(request, 'youxi/youxi.html', {'data': a.counter, 'items': items})


@csrf_exempt
def shuji(request):
    items = Product.objects.filter(category='书籍画报')
    a = Counter.objects.get(id=1)
    return render(request, '书籍画报/书籍画报.html', {'data': a.counter, 'items': items})


@csrf_exempt
def yingyuan(request):
    items = Product.objects.filter(category='应援物')
    a = Counter.objects.get(id=1)
    return render(request, '应援物/应援物.html', {'data': a.counter, 'items': items})


@csrf_exempt
def hufu(request):
    items = Product.objects.filter(category='护肤化妆')
    a = Counter.objects.get(id=1)
    return render(request, '护肤化妆/护肤化妆.html', {'data': a.counter, 'items': items})


@csrf_exempt
def shuma(request):
    items = Product.objects.filter(category='数码配件')
    a = Counter.objects.get(id=1)
    return render(request, '数码配件/数码配件.html', {'data': a.counter, 'items': items})


@csrf_exempt
def riyong(request):
    items = Product.objects.filter(category='日用百货')
    a = Counter.objects.get(id=1)
    return render(request, '日用百货/日用百货.html', {'data': a.counter, 'items': items})


@csrf_exempt
def fuzhuang(request):
    items = Product.objects.filter(category='服装鞋包')
    a = Counter.objects.get(id=1)
    return render(request, '服装鞋包/服装鞋包.html', {'data': a.counter, 'items': items})

Camelot/templates/dongman/dongman.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.1.3-dist/css/bootstrap.min.css' %}">
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">#}
    <meta charset="UTF-8">
    <title>动漫</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item ">
                    {#                    <a class="nav-link" href="#">欢迎来到周边小站 <span class="sr-only">(current)</span></a>#}
                    {% if user.is_authenticated %}
                    <p class="nav-link" style="box-sizing: border-box;    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;    -webkit-tap-highlight-color: transparent;    list-style: none;text-align: -webkit-match-parent;text-decoration: none;
    background-color: transparent;    display: block;
    padding: .5rem 1rem;    padding-right: .5rem;
    padding-left: .5rem;margin-bottom: 0;">hello~ {{ user.username }} Welcome to Camelot!</p>
                    {% else %}
                    <p style="box-sizing: border-box;    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;    -webkit-tap-highlight-color: transparent;    list-style: none;text-align: -webkit-match-parent;text-decoration: none;
    background-color: transparent;    display: block;
    padding: .5rem 1rem;    padding-right: .5rem;
    padding-left: .5rem;margin-bottom: 0;">Welcome, new user. Please log in.</p>
                    {% endif %}

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'camelot:login' %}">请登录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'camelot:register' %}">注册</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'camelot:dongman' %}">动漫</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'camelot:youxi' %}">游戏</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'camelot:yingshi' %}">影视</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'camelot:mingxing' %}">明星</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'camelot:xiaoshuo' %}">小说</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'camelot:piaowu' %}">票务</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {% url 'camelot:liuyan' %}">留言</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'camelot:shoppingcart' %}">我的购物车</a>
                </li>
            </ul>
        </div>
    </nav>



    <br>

<div class="container" style="justify-content: center;">
    <div class="row">
        {% for item in items %}
            <div class="col">
                <div class="card" style="width: 100%;">
                    <img class="card-img-top " src="{{ item.imagesrc }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.name }}</h5>
                        <p class="card-text">{{ item.jieshao }}</p>
                        <a href="{% url 'camelot:detail' item.productid %}" class="btn btn-primary">查看详情</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
</div>











    <div class="container" style="height: 96px; border-top: 2px solid #ed3f3f;">
        <div class="row">
            <div class="col">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-3"><img src="{% static 'img/cangshu.png' %}" style="margin-top: 25px;"></div>
                        <div class="col"><span class="text-center" style="    line-height: 96px; font-size: 18px; font-weight: bolder;">首次下单免邮</span></div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-3"><img src="{% static 'img/cang2.png' %}" style="margin-top: 25px;"></div>
                        <div class="col"><span class="text-center" style="    line-height: 96px; font-size: 18px; font-weight: bolder;">自营69元包邮</span></div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-3"><img src="{% static 'img/cang3.png' %}" style="margin-top: 25px;"></div>
                        <div class="col"><span class="text-center" style="    line-height: 96px; font-size: 18px; font-weight: bolder;">7天退货保障</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="container" style="border-top: 5px solid #e1e1e1;">
        <div class="row">
            <div class="col">
                <div class="container-fluid" style="background: red;">
                    <p class="text-center" >本站浏览次数：{{ data }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row" style="justify-content: center;">
            <p class="mt-5 mb-3 text-muted">&copy; 群星</p>
        </div>
    </div>

    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.3-dist/js/bootstrap.min.js' %}"></script>
</body>
</html>